### ISSUE TITLE
Docker image to facilitate easy development and contributions

### ISSUE THREAD

**Issue by So-Cool** [cuckoosandbox/cuckoo#1026]
It seems that we're missing a way to easily set-up a development environment for Cuckoo. One way would be to create a Docker or Vagrant image. Any suggestions?

**Comment by jbremer** [comment]
As part of #863 it'll already possible to do `pip install cuckoo`, which personally I think is good enough.
Vagrant itself is running VirtualBox, and you don't really want to nest VMs (assuming one runs VirtualBox for the Guest VMs). I believe some hacks are required to get Cuckoo in the Docker image to work with a VirtualBox instance on the host, so that may need some additional documentation there.

That said, I'm fine with not going for the docker image. Any people that argue otherwise? :-)

**Comment by jbremer** [comment]
Closing as this won't be going through if you ask me :-) Please reopen if anybody has a different opinion.
