### ISSUE TITLE
Anyone can help me to add a stop command to Cuckoo?

### ISSUE THREAD

**Issue by Ryuchen** [cuckoosandbox/cuckoo#1112]

**Comment by doomedraven** [comment]
ctrl+c?

**Comment by Ryuchen** [comment]
No, I mean to start cuckoo like python cuckoo.py --start to start cuckoo and use --stop to stop a already running cuckoo

**Comment by doomedraven** [comment]
that not exists,

```
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-q", "--quiet", help="Display only error messages", action="store_true", required=False)
    parser.add_argument("-d", "--debug", help="Display debug messages", action="store_true", required=False)
    parser.add_argument("-v", "--version", action="version", version="You are running Cuckoo Sandbox {0}".format(CUCKOO_VERSION))
    parser.add_argument("-a", "--artwork", help="Show artwork", action="store_true", required=False)
    parser.add_argument("-t", "--test", help="Test startup", action="store_true", required=False)
    parser.add_argument("-m", "--max-analysis-count", help="Maximum number of analyses", type=int, required=False)
    parser.add_argument("-u", "--user", type=str, help="Drop user privileges to this user")
    parser.add_argument("--clean", help="Remove all tasks and samples and their associated data", action='store_true', required=False)
    args = parser.parse_args()
```

**Comment by jbremer** [comment]
If you use the upcoming Cuckoo `package` (#863), then you can take a look at the following documentation (they represent the docs for the `package`): https://cuckoo.sh/docs/usage/start.html#cuckoo-in-the-background.

**Comment by Ryuchen** [comment]
Thanks. I had see that, and now I tried to add a start and stop command to the cuckoo, But I failed. So I want to know anyone who have the same idea with me here. Did the Cuckoo package will be merge in next release?

**Comment by jbremer** [comment]
It will be released after our upcoming `2.0-rc2` release, as there is still a lot of work to be done in the package (it also features a bunch of new stuff).

**Comment by jbremer** [comment]
Right now you can create, e.g., `Upstart` scripts (see also `utils/service.sh`) to do start/stop functionality. Closing this issue as we won't be doing any additional work on this for the current master branch.

**Comment by T0mAl3x** [comment]
Hello! It has been a while since this topic is closed. Any chance to stop (no Ctrl - C) a running analysis in 2.0.6 version? If this is possible, how can I make this happen from cuckoo web interface?

**Comment by doomedraven** [comment]
no way for that, you need to customize it for that

**Comment by T0mAl3x** [comment]
Ok. Before I start, what modules should I investigate in order to stop cuckoo but also to obtain the report after I stop it? Use case example: (From web interface) 1. Presubmit file 2. Choose some options 3. Press Analyze. After that it redirects to a table with analysis statuses. That is where I want to put a stop button. From there I want to costumize a flow so that the stop action doesn't look forced (like CTRL-C to cuckoo process) and obtain a report with analysis information obtained before I stopped the process

**Comment by RicoVZ** [comment]
@T0mAl3x Do you want to stop a specific analysis from the web interface or want to stop the Cuckoo process entirely?

If looking to do the first, there has be to some way of cleanly stopping the Cuckoo analyzer (components that starts the sample in the VM) and there is not yet. Since its design depends on a start->analyze->stop, it does not take into account the use-case of stopping in the middle of an analysis.

That said, you can also do it in a less clean way, but this one is very easy. Change the status of the the task row in the Guest table. This will cause the following check to stop the analysis: https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/core/guest.py#L526

**Comment by T0mAl3x** [comment]
@RicoVZ It worked
I don't know how clean the solution is but here is what I've done:
1. Put a button in the head of the table
2. Added a jquery function which uses ajax to call a post method in analysis/api/tasks/stop
3. Implemented the function in controllers/analysis/api.py which changes the status of the task to "stop"

Note1: It seems that every time i try to submit a file, the table with running tasks contains only the recent submitted task. No matter if 2 tasks are running in paralel on 2 different guests. The web interface needs a few adjusments. For example, this table can only be accesed from interface after the "Analyze" button click. If I want to see it again, I need to fill out the url with the respective path.

Note2: I took advantage of Note1 and the implementation of stop_analysis is similar to api/tasks/info to stop only one task
