### ISSUE TITLE
javascript file analyse error

### ISSUE THREAD

**Issue by arulraji** [cuckoosandbox/cuckoo#1161]
when i try to submit the javascript file it will throw the following error. 

"DEBUG: Error resolving function jscript!COleScript_Compile through our custom callback."
"DEBUG: Error resolving function jscript!ActiveXObjectFncObj_Construct through our custom callback."

is there any problem in my analyse setup? 

sample malware file is attached here
[test.txt](https://github.com/cuckoosandbox/cuckoo/files/575071/test.txt)

**Comment by jbremer** [comment]
No, this is not necessarily an issue. It just means that you have a version of `jscript.dll` that's currently not supported for in-depth hooks that we place. In the future we'll offer users with this issue to directly share their DLL versions to the core developers so that we can add support for those new versions right away.
Closing as to be improved in the future. For now please ignore this message.

**Comment by yasser-alhawary** [comment]
have the same issue here
