### ISSUE TITLE
Failed to save IRMA results in ElasticSearch

### ISSUE THREAD

**Issue by r00t0vi4** [cuckoosandbox/cuckoo#1217]
```
[elasticsearch] WARNING: POST /cuckoo-2016/cuckoo?op_type=create [status:400 request:0.017s]
[lib.cuckoo.core.plugins] WARNING: The reporting module "ElasticSearch" returned the following error: Failed to save results in ElasticSearch for task #19: TransportError(400, u'mapper_parsing_exception', u'object mapping for [irma.probe_results.results] tried to parse field [results] as object, but found a concrete value')
```

**Comment by swackhamer** [comment]
If you are using ES 2.0 try: https://github.com/cuckoosandbox/cuckoo/pull/1196

Make sure to delete your Cuckoo index and delete your dynamic template with the following commands (pointed to the ES server)

```
curl -XDELETE http://localhost:9200/_template/cuckoo_template
curl -XDELETE http://localhost:9200/cuckoo-*
```

If you are on ES 5.0 I should have a fix out soon.

**Comment by razuz** [comment]
just moved to 5.x ... and monitoring for that bug

**Comment by razuz** [comment]
alright ... seeing this bug and working on a fix ... will take a few days to test that

**Comment by razuz** [comment]
so this is odder than expected ... the whole drama is due to simple thing that values change their type as they go ... and to make it even more wierd then values change from string to object even ...

anyways @r00t0vi4 - can you check if such patch fixes your issue : 
https://github.com/cuckoosandbox/cuckoo/compare/master...razuz:irma_es_fix

**Comment by jbremer** [comment]
I'm going to close this issue as resolved by @razuz, I'll be merging his PR soon'ish :-)
