### ISSUE TITLE
Close the cuckoo terminals automatically

### ISSUE THREAD

**Issue by Comchees** [cuckoosandbox/cuckoo#1236]
Hi there,

is it possible to close the cuckoo.py Terminal and the submit.py Terminal after a successfull finished analyse? How can I close the terminals?
I called cuckoo.py and submit.py with subprocess.call. Now I'm trying to figure out how to kill the process. The Methods  kill() and terminate() wont work.. :(

**Comment by jbremer** [comment]
Well, `subprocess.call(...)` is a blocking call, so that's never going to work. You may want to try `subprocess.Popen(...)`. Aside from that, whatever it is you're doing is probably not the best way to approach the problem. Perhaps you'd like to share a bit more information on that? And also did you already resolve this issue by now?

**Comment by Comchees** [comment]
Yeah I already fixed the problem by using `subprocess.Popen(...)` and then killing the process by PID. The Idea was to generate a Tasklist of many malwaresamples and giving them to cuckoo.
