### ISSUE TITLE
Cuckoo and ElasticSearch

### ISSUE THREAD

**Issue by iyerabhi07** [cuckoosandbox/cuckoo#1240]
I am trying to send cuckoo data to ES. I am getting the below error:
WARNING: The reporting module "ElasticSearch" returned the following error: Failed to save results in ElasticSearch for task #9: TransportError(400, u'action_request_validation_exception', u'Validation Failed: 1: an id must be provided if version type or value are set;')

What am I doing wrong? Any setting that I need to change?

**Comment by doomedraven** [comment]
see https://github.com/cuckoosandbox/cuckoo/issues/1178

**Comment by MarkusTeufelberger** [comment]
Currently only ES 2, not ES 5 works, https://github.com/cuckoosandbox/cuckoo/pull/1196 will probably fix this, once it gets merged.

**Comment by swackhamer** [comment]
ES 5 requires you to specify the id if using the "create" call.  This is fixed in #1196 but we are still having issues indexing a subset of samples in 5.x.  However that PR (right now) allows you to use ES 5 client library and ES 2 server without any issues.  It also includes other fixes for the ES reporting module.

**Comment by iyerabhi07** [comment]
Apologies for the late reply. Thanks @swackhamer @MarkusTeufelberger @doomedraven . I will follow that thread to see what comes of it.

**Comment by doomedraven** [comment]
so probably time to close it ? ;)
