### ISSUE TITLE
[Question] Json report fields info->started/ended and info->machine->started_on/shutdown_on - host time or guest time?

### ISSUE THREAD

**Issue by GranolaMaster** [cuckoosandbox/cuckoo#1309]
Hi,

I have a custom analysis package which runs on the guest (inside the analysis VM) and logs data to a database, along with an epoch timestamp for each record. After running lots of samples, I then sync these records up to the tasks processed by Cuckoo using the information in their report.json files. Specifically I convert the time in the info->machine->(started_on and shutdown_on) fields to epoch time and then try to match those times with the timestamps for the data in the database. However, I realised the other day that the time as perceived by the VM is different to the time as perceived by the host by a couple of seconds. Hence it is important to know: are the info->machine->started_on/shutdown_on and info->started/ended fields in the report.json file times relative to the guest or relative to the host? I would assume that they are logged in the guest and sent back to the host using the ResultServer (and hence that these times would be relative to the guest), but I can't work out where in the Cuckoo code this happens. The times logged in the database are relative to the guest, as I assume would be the times of packets sent/received and of api calls, so it would be a lot easier for my progrom if the start/end times are from the perspective of the guest too...

Thanks.

**Comment by jbremer** [comment]
They're set on the host as can be seen in the database code https://github.com/cuckoosandbox/cuckoo/blob/a1382cac2300e3c22ba62f9339e7a50aec40ea8b/cuckoo/core/database.py#L624-L627.
Note that the time in the guest is subject to change and per-analysis modification, i.e., it's possible for a user to set the guest clock to the year 2001 or 2020 on a per-analysis basis, so using that date/time wouldn't be very appropriate.
What I do think we should do is move all of the times that come out of the Guest to relative time stamps, rather than absolute ones, but this will be a slightly bigger change for the future.

Does this answer your question(s)? Thanks!

**Comment by jbremer** [comment]
Closing issue for lack of additional information, feel free to reopen if you have new insights. Thanks!
