### ISSUE TITLE
Error getting access to process: 5!

### ISSUE THREAD

**Issue by orlandohealth** [cuckoosandbox/cuckoo#1310]
Hi guys,

We're new to Cuckoo Sandbox, we just installed it a week ago on an Ubuntu 16.04 host and we're happy with it so far. We're using Windows 7 32bit physical guest machines for malware analysis with Deep Freeze installed  on them.

Everything is working fine except when we submit a malware for analysis, the error "Error getting access to process: 5!" appears on the guest and the only way to continue with the malware analysis is to acknowledge the error, we've tried all the solutions found on the forum related to this issue from disabling UAC, to running agent.py as Administrator but nothing worked, the only work around that we have done so far is to comment the code in analyzer/windows/modules/auxiliary/dumptls.py as per issue #1019 which makes the error disappear. We get the same error when we run the command "is32bit.exe -n lsass.exe" as administrator, we've also tested with Windows 7 without service pack and Windows XP SP3 guests all without any updates installed but no luck so far.

I'm not sure what the code in dumptls.py does and if it is a good idea to comment it?

Any help in solving this issue is highly appreciated.

Thanks.

**Comment by jbremer** [comment]
Hi! So I'm not sure about a fully patched Windows 7, but Windows XP & unpatched Windows 7 should most certainly work without issues. We've been contemplating if it makes sense to get rid of the message box thingy (it 99% certainly does), but so far we haven't put too much effort into it because we never really run into this situation ourselves.
Can you perhaps show a screenshot of running `is32bit.exe` in an Administrator shell? It just doesn't make a lot of sense, really. On Windows 8+ I see possibilities for this failure to happen (even if we've had successful stories regarding such environment), but on Windows 7, let alone Windows XP, this most certainly shouldn't happen.
Thanks!

**Comment by orlandohealth** [comment]
Definitely, here's the screenshot, the logged on user is the local Administrator account, UAC is off, OS is Windows 7 SP1 without any patches installed.

![screenshot](https://cloud.githubusercontent.com/assets/26149262/23551650/c2579bea-ffe5-11e6-9b60-dd723363f588.jpg)

**Comment by orlandohealth** [comment]
The only difference I could see is, we're using physical guests instead of VMs, typically they should work the same, I don't see how that makes a difference unless I'm missing something.

**Comment by orlandohealth** [comment]
By the way, the Windows 7 that I've tested on wasn't patched at all. Sorry for the confusion.

**Comment by jbremer** [comment]
So lately we've been putting in some work to get rid of the message box as well as the need to inject into `lsass.exe` - the only aspect that really needs `Administrator` rights. After merging those changes into the next alpha or stable release, I hope to have resolved this issue. Would you be up for testing in the near future?

**Comment by jbremer** [comment]
Closing issue as it has been resolved by the solution stated above, which was released as part of our `2.0.4` release. Please let us know if you have additional questions or feedback. Thanks!
