### ISSUE TITLE
Elasticsearch setup?

### ISSUE THREAD

**Issue by RANGERBEE** [cuckoosandbox/cuckoo#1471]
Does someone have  steps or a quick script to setup elasticsearch correctly for the current cuckoo instance?  2.0.2a3

Thanks!!

**Comment by RANGERBEE** [comment]
https://gist.github.com/ricardo-rossi/8265589463915837429d

**Comment by doomedraven** [comment]
insatll is one thing, make it work with cuckoo is another xD

**Comment by RANGERBEE** [comment]
Oh so true!!!!! ;)

**Comment by SparkyNZL** [comment]
Isn't that for es 1.7 ?

Cuckoo uses 5.x



Sent from my spaceship...

On 25/04/2017 5:59 AM, "doomedraven" <notifications@github.com> wrote:

insatll is one thing, make it work with cuckoo is another xD

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cuckoosandbox/cuckoo/issues/1471#issuecomment-296771564>,
or mute the thread
