### ISSUE TITLE
VBoxManage Error - Windows 10

### ISSUE THREAD

**Issue by Waffles-2** [cuckoosandbox/cuckoo#1478]
When trying to setup Cuckoo on a Windows machine, I am getting the error `Error initializing machines: VBoxManage error listing installed machines: [Error 5] Access is denied`

Not too sure what is causing this as I can manually run VBoxManage from command prompt and get the list of installed machines using `VBoxManage list vms`.

**Comment by SparkyNZL** [comment]
Make sure the cuckoo user is either the owner of ur vm or the cuckoo user
is in the group which owns your VM. DONT run cuckoo as root

Cherrs

Sent from my spaceship...

On 25/04/2017 10:49 PM, "Daniel Perrie" <notifications@github.com> wrote:

When trying to setup Cuckoo on a Windows machine, I am getting the error Error
initializing machines: VBoxManage error listing installed machines: [Error
5] Access is denied

Not too sure what is causing this as I can manually run VBoxManage from
command prompt and get the list of installed machines using VBoxManage list
vms.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cuckoosandbox/cuckoo/issues/1478>, or mute the thread

**Comment by Waffles-2** [comment]
I wasn't running cuckoo as root but when I do I get the same error. How do I ensure the cuckoo user is the owner of the VMs?

Just a note, at this point cuckoo isn't trying to launch any VMs it is simply trying to list the virtual machines in the VirtualBox library.

**Comment by jbremer** [comment]
Exactly. Why it fails is a mystery to me, though. At the moment I don't have a Windows machine on me to try it out, but we'll give it a spin one of these days. Do also consider switching to a Linux system :)

**Comment by Waffles-2** [comment]
This is a little crazy but just hear me out. So there is a line in `virtualbox.py` under `_lists`. 

`self.options.virtualbox.path, "list", "vms"` this outputs `C:\Program Files\Oracle\Virtualbox\VBoxManage.exe list vms` so I just added a line that would do:

`subprocess.call(C:\Program Files\Oracle\Virtualbox\VBoxManage.exe list vms)` 

Which oddly works fine and we don't get an access denied error. So I deleted the line I added into `virtualbox.py` and deleted `args = [self.options.virtualbox.path, "list", "vms"]` then re-typed out `args = [self.options.virtualbox.path, "list", "vms"]` and surprise it is working with no errors. 

Literally just retyping the line fixed the problem. Obviously this is crazy and shouldn't have worked, but I am not complaining as it is working now.
