### ISSUE TITLE
Fetched reports in Distributed Cuckoo lack of data

### ISSUE THREAD

**Issue by nguoicaotuoi** [cuckoosandbox/cuckoo#1524]
Hi all,

I set up Distributed Cuckoo (2.0.1) as following: http://docs.cuckoosandbox.org/en/latest/usage/dist/#setup-distributed-cuckoo

When tasks were finished on Nodes, report files were sent to [reports_directory] set in distributed/settings.py on the Distributed Cuckoo machine (called the Masternode) and all task-related data (include screenshots, pcap files,...) were removed from the Nodes.
The problem is on the report files fetched to the Masternode: 
- In the file report.html, there are too litte data (just 4 of 100 screenshots, no network dump info,...)
- In the file report.json, data seem to be sufficient but screenshots are paths to jpg files on the Nodes, which have been removed immediately after the Masternode fetched the reports.

I want all the task's report data that generated on the Nodes can be fetched and viewed on the Masternode, what can I do?

All related configs and some report samples can be downloaded from: https://drive.google.com/file/d/0BxOZbVnnSgncbzZnaTVxWjVXYWM/view?usp=sharing

Thank you! (And sorry if my English was bad.)

**Comment by jbremer** [comment]
You can write some additional code to handle that ;-) Easiest would probably be a Cuckoo reporting plugin that `.zip`'s up all the information that you want for an analysis and then have Distributed Cuckoo fetch that file for you. The reason Distributed Cuckoo returns so little information is the simple fact that, in a highly automated and mass-analysis setup, there's simply no use-case for *all* of the small details that make up for every report.
We could consider a feature where the original reports (on a node) are deleted after X hours or days rather than immediately so you have a chance of seeing it before it gets removed, but this would require a fair amount of diskspace on each node.
What are your thoughts? Thanks for the feedback!

**Comment by doomedraven** [comment]
Or port my dist.py which works just fine and will show all info in master node ;)

**Comment by nguoicaotuoi** [comment]
@doomedraven Did you mean this? https://github.com/doomedraven/cuckoo-modified/blob/master/utils/dist.py

@jbremer Yeah I agree with you :) The best way to satisfy my wants is to write custom code.

Thank you all for your responses!

**Comment by doomedraven** [comment]
@nguoicaotuoi yup, the main difference i think is only change `task_ids` to `task_id` or vice-versa and should be fine to go 

here is the latest version https://github.com/spender-sandbox/cuckoo-modified/blob/master/utils/dist.py

**Comment by nguoicaotuoi** [comment]
@doomedraven Well thanks man! I'm going to try it now :) Closing this issue as resolved.

**Comment by doomedraven** [comment]
i tried it in past with rc2 and it worked with only that change, they could change something else, if yes, let me know as that will be my dist.py for v2 too :D I prefer the idea of having all results in master and not in just files without using api etc :)

**Comment by doomedraven** [comment]
ah and one more things, check `dist` and `dist2` formats in apis to add all files which you want or don't want to retrieve and you need this api.py

https://github.com/spender-sandbox/cuckoo-modified/blob/master/utils/api.py as we trick it to work with dist.py, but should be identical or almost identical to v2 api.py
