### ISSUE TITLE
rooter crashes if yara rules fail to compile

### ISSUE THREAD

**Issue by seanthegeek** [cuckoosandbox/cuckoo#1654]
If yara rules fail to compile `rooter` will crash shortly after starting, which will cause the cuckoo and web app processes to report failure to start due to rooter not running, but concealing the true root of the problem.

**Comment by jbremer** [comment]
Heh, interesting. I'm rewriting some of the Yara stuff, let's see if this is still an issue afterwards.

**Comment by jbremer** [comment]
To be honest I'm not seeing the `cuckoo rooter` crash when invalid Yara rules are loaded. That would also be a bit weird, since Yara rules (or any additional modules, really) aren't loaded when one invokes `cuckoo rooter`.
Could you share some logs or so in which you can clearly identify this behavior?

**Comment by seanthegeek** [comment]
Turns out it kept "crashing" because the systemd script I wrote for it kept trying to restart all of the cuckoo services when Cuckoo would exit after throwing the yara error. Never mind
