### ISSUE TITLE
Web interface setup

### ISSUE THREAD

**Issue by MigliS** [cuckoosandbox/cuckoo#1781]
Hi there!
It's me again. I have a second issue already. 
I cant' reach the cuckoo web interface via an ip address and port.
It says page can't be displayed.
I installed uwsgi and nginx.

**Comment by doomedraven** [comment]
don't use cuckoo with sudo!

**Comment by MigliS** [comment]
Doesn't solve my problem...

**Comment by MigliS** [comment]
And if I want to run `cuckoo web runserver`, error message 

> In order to use the Cuckoo Web Interface it is required to have MongoDB up-and-running and enabled in Cuckoo. Please refer to our official documentation as well as the $CWD/conf/reporting.conf
MongoDB is installed and running and I created a database called cuckoo a shown in the reporting.conf.

**Comment by Nwinternights** [comment]
Dont create mongodb db because when It starts cuckoo Will create It. Go to config and choose another name for the DB(ES cuckoo2) . For the web part try : cuckoo web -H (IP HOST) -p (listen port). Start 2 screen/term One for cuckoo One for web . To see if mongodb is running:   ps -edaf | grep mongo | grep -v grep  
or
   /etc/init.d/mongod status
or
   service mongod status

**Comment by MigliS** [comment]
Thank you Nwinternights, it worked 👍

**Comment by doomedraven** [comment]
close if solved? ;)

**Comment by maorkadosh1** [comment]
Thanks

**Comment by ESL482** [comment]
Hi ,
 i am new to cuckoo sandbox, i installed cuckoo and it's running fine when i run the cuckoo web runserver my ip_adreess:port but now i want to connect my cuckoo with nginx and i want provide authentication using nginx.please suggest
