### ISSUE TITLE
How to replace base64 decoded strings?

### ISSUE THREAD

**Issue by super-a1ice** [cuckoosandbox/cuckoo#1783]
The string matching the Yara rule is displayed in Base64 format.
Should I decode when displaying it as HTML?
![cuckoo-web](https://user-images.githubusercontent.com/2360691/29358624-a34e53d4-82b6-11e7-8a64-863565d81ef4.png)

**Comment by doomedraven** [comment]
read the documentation how to develop a custom module, and do replace and decode in it

**Comment by jbremer** [comment]
@tatsui You're correct. I think I'll ask @automagisch to decode the base64 in the frontend.

**Comment by iamcerdo** [comment]
I found this issue when searching for the (same) problem I was having. For whatever it's worth, I also feel that this should be handled in the front end. 

As a temporary workaround, in my local install, I added the following to cuckoo/web/analysis/templatetags/analysis_tags.py:


```
import base64

@register.filter
def b64dec(value):
    return base64.b64decode(value)
```
Then updated line 46 of cuckoo/web/templates/analysis/pages/procmemory/index.html to use the b64dec filter, as opposed to the raw string:
```
{{string|b64dec}}
```
Example output: 

![dc1](https://user-images.githubusercontent.com/37192172/37172162-084d6456-22de-11e8-9062-9dacd1df5f7b.png)

With that said, I prefer something like the DarkComet configuration block to be pre-formatted instead of in an unordered list, so some kind of feature that allows different types of output might be more appreciated. 

For example, here's what it looks like once I updated cuckoo/web/templates/analysis/pages/procmemory/index.html to output as pre-formatted as opposed to an unordered list:

![drkc](https://user-images.githubusercontent.com/37192172/37172010-9ba2ff32-22dd-11e8-89ea-c97b0206ec1e.png)
