### ISSUE TITLE
What does mean score ?

### ISSUE THREAD

**Issue by jaidls** [cuckoosandbox/cuckoo#1885]
i don't understand score , how to measure score ?
what are the standard in measure score?
Are high or low scores malicious code?

**Comment by RicoVZ** [comment]
Hi jaidls,

The score is calculated by adding up the severity levels of each matched Cuckoo signature and dividing it by 5.0. The difference in score means different signatures (fewer, more or others) are matched.

The signatures are matched against all collected data (behavioral etc). Since behavioral data can differ per analysis, it means different signatures can match. This can result in a different score for analyses of the same file.

A high score can idicate a file is malicious. To really judge about that, you would also need to see what signatures were matched. The same goes for a low score, it does not mean a file is not malicious.

**Comment by jbremer** [comment]
Closing as resolved.
