### ISSUE TITLE
Score issue

### ISSUE THREAD

**Issue by gabbiano83** [cuckoosandbox/cuckoo#1974]
Hi,

I'm using 2.0.4 Cuckoo version, and I'm facing a issue related to score calculation.
The calculated score is different even submitting the same sample on same conditions.
There is a reason for that?
How the score is calculated?

**Comment by RicoVZ** [comment]
Hi gabbiano83,

This is indeed possible. The score is calculated by adding up the severity levels of each matched Cuckoo signature and dividing it by 5.0. The difference is score means different signatures (fewer, more or others) are matched.

The signatures are matched against all collected data (behavioral etc). Since behavioral data can differ per analysis, it means different signatures can match. This can result in a different score.

**Comment by jbremer** [comment]
We intend to improve the scoring system further, but yes, it may indeed differ slightly between analyses. Any more questions @gabbiano83 or do you have enough information?

**Comment by gabbiano83** [comment]
It's enough,
I'm working on a malware classification project using cuckoo sandbox, it's a really impressive tool.

thank you for your support

**Comment by jbremer** [comment]
No worries, you're welcome. Thanks!
