### ISSUE TITLE
CRITICAL: CuckooConfigurationError (Suricata)

### ISSUE THREAD

**Issue by hackdefendr** [cuckoosandbox/cuckoo#2018]
Please do not state the obvious, because the configuration IS correct. Cuckoo just refuses to accept it and start unless I disable Suricata. But I need Suricata data in my analysis, so this should be fixed.

`2017-12-16 14:20:53,359 [cuckoo] CRITICAL: CuckooConfigurationError: The configuration value '"/etc/suricata/suricata.yaml"' found for processing:suricata:conf is invalid. Please update your configuration!`

**Comment by RicoVZ** [comment]
Hi hackdefendr, thanks for posting your issue.

The error you have posted is not referring to the actual Suricata config being invalid. It is referring to the value for `conf` under suricata in processing.conf.

Upon startup, Cuckoo performs multiple checks, including the verification of each configuration value of enabled modules. In your case, I suspect the double quotes are causing the issue here. None of the Cuckoo configuration values should be quoted, all values are read as strings and changed to the correct type by Cuckoo.

To fix the issue you are experiencing, I suggest changing the value for `conf` under `[suricata]` in your processing.conf from `"/etc/suricata/suricata.yaml"` to `/etc/suricata/suricata.yaml`.

Cuckoo is aware of this being a path and thus also verifies if is exists and if it is readable. If my suggested solution does not work, please also check if the file exists and is readable for the user executing Cuckoo.

**Comment by hackdefendr** [comment]
As I stated...my configuration is correct. There are no quotes around the path in the configuration file, and the suricata.yaml file does exist. This just started with the latest update.

**Comment by hackdefendr** [comment]
Additionally...I get the same error when I enable snort. Again, my configuration is correct, the files exist where they are supposed to be, Cuckoo just won't accept this and start up.

**Comment by doomedraven** [comment]
after so many complains about sirucata, i decided to test it on my side, it works just fine
```
╰─○ suricata -V
This is Suricata version 4.0.3 RELEASE
``

```
[suricata]
enabled = yes
# represent the defaults.
suricata = /usr/bin/suricata
conf = /etc/suricata/suricata.yaml
eve_log =  eve.json
files_log = files-json.log
files_dir = files
socket =

```

**Comment by doomedraven** [comment]
my suggestion to get your bug is
execute any report reprocess with strace and grab all logs(childs included -ff) and grep for suricata

**Comment by securedlab** [comment]
I had same error, I changed my config from this:
conf = /etc/suricata/suricata.yaml
To this:
conf = /etc/suricata/debian-suricata.yaml
Then it worked.

**Comment by doomedraven** [comment]
@jbremer maybe just add check if file exist in startup?

**Comment by Foneman38** [comment]
It could be because your cuckoo user doesn't have the correct permissions to read the snort or suricata conf files
