### ISSUE TITLE
 CRITICAL: CuckooDatabaseError

### ISSUE THREAD

**Issue by adhityosenoaji** [cuckoosandbox/cuckoo#2038]
I try to connect cuckoo to my sql but i found error.

Cuckoo Sandbox 2.0.5
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
 You're good to go!

 Our latest blogposts:
 * Cuckoo Sandbox 2.0.5: Office DDE, December 03, 2017.
   Brand new release based on a DDE case study.
   More at https://cuckoosandbox.org/blog/205-office-dde

 * Cuckoo Sandbox 2.0.4, September 06, 2017.
   Introducing Malware Configuration Extraction.
   More at https://cuckoosandbox.org/blog/cuckoo-sandbox-204

 * Cuckoo Sandbox 2.0.0, March 30, 2017.
   First Cuckoo package release!
   More at https://cuckoosandbox.org/blog/cuckoo-sandbox-v2

2018-01-02 08:56:31,592 [cuckoo] CRITICAL: CuckooDatabaseError: Unable to create or connect to database: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' (10061)")

MySql is running, how to solve this?

**Comment by doomedraven** [comment]
do you able to connecto to mysql without cuckoo?

**Comment by adhityosenoaji** [comment]
yes, i can create database, create user, etc.

**Comment by jbremer** [comment]
Well, it's saying it can't connect to MySQL. Perhaps you have a different host or port?

**Comment by RicoVZ** [comment]
Hi @adhityosenoaji, are you still having this issue?
If you, please post your MySQL listening port and ip, and the database connection string (Without password) from your `cuckoo.conf`.

**Comment by Hesham-Salama** [comment]
I don't know if OP still has have this issue, but anyway I had the exact issue. What worked for me:

In cuckoo.conf, use `connection = mysql://username:password@127.0.0.1/mydatabase` instead of `localhost` in that file `mysql://username:password@localhost/mydatabase`

Also of course make sure you have run those commands to make localhost avaliable:

`sudo service apache2 start`
`sudo service mysql start`
`sudo service mongodb start`

**Comment by jbremer** [comment]
Closing issue as resolved (Database wasn't actually running).
