### ISSUE TITLE
storage after analysis

### ISSUE THREAD

**Issue by ahmad67** [cuckoosandbox/cuckoo#2106]
hi , can anyone tell me why when i finished analysis  analysis take from my HD 348 MB for one malware why ? i need to analysis 200k malwares in this rate i need 100 TB !!! 
i use mysql as database

**Comment by doomedraven** [comment]
go to analysis folder and see al files, and you will know why

**Comment by SparkyNZL** [comment]
You can start to turn some functionality off like html / PDF report. Memory and process memory dumps etc. Think about what you need not what you want.








sent from my SpaceShip... =[][][][]>







On Mon, Feb 5, 2018 at 9:16 AM +1300, "doomedraven" <notifications@github.com> wrote:












go to analysis folder and see al files, and you will know why

**Comment by RicoVZ** [comment]
Hi ahmad67,

Indeed an anaysis can take up that much space, it can take up even more.
This is because each API call the malware executes, including all its arguments, is being stored.

A large portion of the size of the total report is often the API calls section in the JSON report.

There is a way to reduce the size of the JSON reports. That is, if you don't mind the API call logs missing from the them. The calls tend to be the force behind large reports.

The option `json.calls=0` can be added when submitting a task. It is also possible to completely disable API calls in the JSONreport. You can do this by changing `calls = yes` in reporting.conf to `calls = no`, This setting is located under `[jsondump]`.

How much you can reduce the results all depend on what information you do need/your goal. Each reporting module can be disabled if not required.

**Comment by jbremer** [comment]
Closing issue. There are many things that can be done and you don't necessarily need to keep all data if you want to analyze 200k malware samples. Feel free to reopen issue if you have more specific requests.
