### ISSUE TITLE
IRC Site Down?

### ISSUE THREAD

**Issue by ewalkup** [cuckoosandbox/cuckoo#2111]
This probably isn't the best place, but I don't know where else to ask.

Cuckoo's chat site, https://irc.freenode.net, seems to have been down every time I've checked it for the past couple of weeks.

![screen shot 2018-02-05 at 12 24 14 pm](https://user-images.githubusercontent.com/13425774/35824194-58a76352-0a6f-11e8-9a09-2d0b3cc20eae.png)

I assume you guys don't run that site, but it would be nice to be able to ask setup questions somewhere other than here...are there any alternative IRC sites?

Secondary note: I couldn't search for a different way to submit this question, because the main site has an invalid certificate:

![screen shot 2018-02-05 at 12 23 47 pm](https://user-images.githubusercontent.com/13425774/35824252-899f024e-0a6f-11e8-8ddd-b7b3fa59b481.png)

**Comment by jbremer** [comment]
You can try the Webchat from freenode; https://webchat.freenode.net/. Alternatively you can just post your issues & questions here. We're more active here anyway ;-)

**Comment by ewalkup** [comment]
Thanks - wasn't sure if the GitHub should be reserved for code issues.

**Comment by seantree** [comment]
Hi @ewalkup I saw your repository of cuckoo for mac osx sandbox, I just want to know is it working perfectly? for mac binaries?
Waiting for positive reply

**Comment by ewalkup** [comment]
@seantree It works for FAT and Mach-O executables, 'perfectly' may be a relative term. It will collect the main things Cuckoo for Windows does (behavior/new processes/dropped files/screenshots/static analysis).   

However, it is worth noting that it's about 3 years old (there was over a year between when I developed it and when it got open-sourced), and I have not been actively working on it since Cuckoo started work on their own Mac analyzer, so it might lack some features of Cuckoo 2.0 (which didn't exist when I made my analyzer).

**Comment by seantree** [comment]
@ewalkup  Thanks for the quick reply I just need one favor from you. I have used your cuckoo Mac repository and replace the file cuckoo 2.0.4 files with your mac files and I have started analysed the mac binaries but there is one issue it doesn't capturing the processes/dropped files/behavior. It only show me the static strings and VT infection part. I have analyzed the macho-64bit binaries.

I was wondering it would be great for me and for other security researchers if you upload the exact folder of cuckoo because in your repositories some files are missing like cuckoo.py and submit.py etc.

Waiting for positive reply.

**Comment by ewalkup** [comment]
@seantree Those files are missing because no changes were made to them - I deliberately uploaded only files that I had modified. If you need the older Cuckoo version files, I developed on Cuckoo version 1.2, which can be downloaded here: https://github.com/cuckoosandbox/cuckoo/releases/tag/1.2

As far as it not catching behavior, that would require a lot more debugging. Another thing to note is that the analyzer was not tested on Mac versions any higher than Yosemite (as that was the highest released at the time of development) and El Capitan especially contained some fairly major system changes. It's also possible that it just doesn't return behavior in the format expected by the 2.0.4 web interface. 

I appreciate the interest in my past work, but want to once again re-iterate that it's not currently under development - so if it needs changes to be compatible with 2.0.4, or to run on newer OS versions, someone else will need to do that work. Someday I may come back to it, but for now I'm trying to work with the Mac analyzer already present in Cuckoo 2.

**Comment by seantree** [comment]
@ewalkup Thanks for the quick reply and the information, Just want to one last thing. I also tried the mac analyzer of cuckoo 2 that's also not working. So if you are working on the current version of cuckoo mac analyzer I just want to give some inputs try to add more packages in it because last time when I tried to use updated cuckoo 2.0.1 to 2.0.4 it's showing me the same issue of package/behaviour/droppedfiles/
.
I will wait for someone who will complete the Mac cuckoo analyzer part with perfect documentation.
.
Thanks & Regards
Seantree
