### ISSUE TITLE
Behavior log file and BsonParser lacking data

### ISSUE THREAD

**Issue by nice9uy** [cuckoosandbox/cuckoo#2116]
Hi..

[cuckoo.processing.behavior] CRITICAL: Behavior log file '3676.bson' is too big, skipped.

and

[cuckoo.common.netlog] CRITICAL: BsonParser lacking data.

there is already a solution in this case?

Thanks

**Comment by doomedraven** [comment]
do search in issues and you will see waht there a lot like this one

**Comment by RicoVZ** [comment]
Hi nice9uy,

Thanks for posting an issue, and sorry for the late reply.

There seem to be two seperate issues here:
The first error is easily solved:

> [cuckoo.processing.behavior] CRITICAL: Behavior log file '3676.bson' is too big, skipped.

It is because the bson file is larger than the maximum size specific in `cuckoo.conf` `analysis_size_limit`. File larger than this limit are ignore during processing. You can increase this limit. Note: larger files will also mean larger reports and longer processing time.

> [cuckoo.common.netlog] CRITICAL: BsonParser lacking data.

This means that during the network communication of transporting logged behavior, the communication was stopped/interrupted. This can mean many things: timeout etc.

**Comment by jbremer** [comment]
Closing issue for lack of additional information - please reopen if you have an update for us.
