### ISSUE TITLE
Can't import anything under lib

### ISSUE THREAD

**Issue by kbm15** [cuckoosandbox/cuckoo#2196]
Hello, I've been trying to make a custom Auxiliary Module that can run RawCopy under my Windows guest, to dump  the sysmon log file.  
The aproach was the following: Use the API to create a new process and pass the arguments.
But we can't as the lib path can't be solved. We can only access functions under cuckoo.  
We are running Cuckoo from a virtual enviroment and most of the docs seems outdated, so I've been following the issues to get a grasp of how to proceed, but I can't go further myself.  

```python
import logging
import json
import os
from cuckoo.common.abstracts import Auxiliary
from lib.api.process import Process 

log = logging.getLogger(__name__)

class Custom(Auxiliary):

    def __init__(self, options={}, analyzer=None):
        Auxiliary.__init__(self)

    def start(self):
        log.info("Starting my Custom auxiliary module")
        path = os.getcwd()
        log.info(path)
    def stop(self):
        log.info("SORE WA, MATA ASHITA")
        #Here is my log"C:\Windows\System32\winevt\Logs\Microsoft-Windows-Sysmon%%4Operational.evtx", "log/sysmon.evtx")
```
  
The error I got on launch is the following:  
  
```
File "/home/cuckoo/cucu/bin/cuckoo", line 7, in <module>
    from cuckoo.main import main
  File "/home/cuckoo/cucu/local/lib/python2.7/site-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/home/cuckoo/cucu/local/lib/python2.7/site-packages/cuckoo/auxiliary/__init__.py", line 10, in <module>
    file, "cuckoo.auxiliary", globals(), Auxiliary
  File "/home/cuckoo/cucu/local/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 46, in enumerate_plugins
    "review its contents and/or validity!" % (fname, e)
cuckoo.common.exceptions.CuckooOperationalError: Unable to load the Cuckoo plugin at custom.py: No module named lib.api.process. Please review its contents and/or validity!
```    
  
My lib folder (I hope this is the one) is located here:   
  

> /home/cuckoo/cucu/lib/python2.7/site-packages/cuckoo/data/analyzer/windows/lib

**Comment by RicoVZ** [comment]
Hi kbm15,

If I understand correctly, you want to develop an additional Auxiliary module that should run inside the guest?

It seems you are running your module on the host machine, instead of on the guest machine. If you want your guest Auxiliary module to run on the guest, you should place it at: `$CWD/analyzer/windows/modules/auxiliary`.

The modules in this location are uploaded and executed in the guest machine for each analysis.

To actually implement the guest auxiliary module, you will need to implement the Auxiliary abstract class from `lib.common.abstracts`, not `cuckoo.common.abstracts`.

https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/data/analyzer/windows/lib/common/abstracts.py#L189

Everything in the `analyzer` folder is only accessible to import for modules inside the guest.

**Comment by jbremer** [comment]
Any update here @kbm15? What @RicoVZ said is correct :)
Will be closing this issue next time if no additional feedback is provided.

**Comment by RicoVZ** [comment]
We will work on updating the docs, thanks for the feedback!

**Comment by jbremer** [comment]
@kbm15 Feel free to help with the documentation aspect though - Cuckoo is an open source project and writing documentation would be done on our free time, too.. Closing as resolved.
