### ISSUE TITLE
Error when running cuckoo

### ISSUE THREAD

**Issue by maorlevi25** [cuckoosandbox/cuckoo#2202]
I didn't have problems before.
Until now it worked good.
After a restart to the server I got this when trying to run cuckoo:

                      __
  .----..--.--..----.|  |--..-----..-----.
  |  __||  |  ||  __||    < |  _  ||  _  |
  |____||_____||____||__|__||_____||_____|

 Cuckoo Sandbox 2.0.5
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

 Checking for updates...
 You're good to go!

 Our latest blogposts:
 * Cuckoo Sandbox 2.0.5: Office DDE, December 03, 2017.
   Brand new release based on a DDE case study.
   More at https://cuckoosandbox.org/blog/205-office-dde

 * Cuckoo Sandbox 2.0.4, September 06, 2017.
   Introducing Malware Configuration Extraction.
   More at https://cuckoosandbox.org/blog/cuckoo-sandbox-204

 * Cuckoo Sandbox 2.0.0, March 30, 2017.
   First Cuckoo package release!
   More at https://cuckoosandbox.org/blog/cuckoo-sandbox-v2

Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.5
OS version: posix
OS release: Ubuntu 16.04 xenial
Python version: 2.7.12
Python implementation: CPython
Machine arch: x86_64
Modules: adium-theme-ubuntu:0.3.4 alembic:0.8.8 androguard:3.0.1 asn1crypto:0.24.0 beautifulsoup4:4.5.3 cairocffi:0.8.0 cairosvg:1.0.22 capstone:3.0.5rc2 certifi:2018.1.18 cffi:1.11.5 chardet:2.3.0 click:6.6 colorama:0.3.7 cryptography:2.2 cssselect:1.0.3 cuckoo:2.0.5.3 distorm3:3.3.0 django-extensions:1.6.7 django:1.8.4 dpkt:1.8.7 ecdsa:0.13 egghatch:0.2.1 elasticsearch:5.3.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.12.2 functools32:3.2.3.post2 html5lib:1.0.1 httpreplay:0.2.2 idna:2.6 ipaddress:1.0.19 itsdangerous:0.24 jdcal:1.0 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:2.6.0 lxml:3.5.0 mako:1.0.7 markupsafe:1.0 meld3:1.0.2 mysqlclient:1.3.7 olefile:0.43 oletools:0.51 openpyxl:2.3.0 peepdf:0.3.6 pefile2:1.2.11 pillow:3.2.0 pip:9.0.2 py:1.4.31 pycparser:2.18 pycrypto:2.6.1 pyelftools:0.24 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:17.5.0 pyphen:0.9.4 pytest:2.8.7 python-dateutil:2.4.2 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 pytz:2014.10 pyvmomi:6.5.0.2017.5.post1 pyyaml:3.12 requests:2.13.0 scapy:2.3.2 setuptools:39.0.1 sflock:0.2.20 six:1.10.0 sqlalchemy:1.0.8 supervisor:3.3.4 tinycss2:0.6.1 tlslite-ng:0.6.0 unicorn:1.0.1 unity-lens-photos:1.0 urllib3:1.22 vboxapi:1.0 virtualenv:15.0.1 vmcloak:0.4.5 volatility:2.5 wakeonlan:0.2.2 weasyprint:0.39 webencodings:0.5.1 werkzeug:0.14.1 wheel:0.29.0 xenapi:1.2 yara-python:3.6.3

2018-03-27 18:24:34,145 [cuckoo] ERROR: ValueError: invalid version number '4'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 230, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 137, in cuckoo_init
    init_modules()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py", line 197, in init_modules
    RunSignatures.init_once()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 348, in init_once
    if cls.should_load_signature(signature):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 360, in should_load_signature
    if not cls.check_signature_version(signature):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 390, in check_signature_version
    if not supported_version(cls.version, sig.minimum, sig.maximum):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/utils.py", line 337, in supported_version
    if minimum and StrictVersion(version) < StrictVersion(minimum):
  File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '4'
.

**Comment by jbremer** [comment]
Thanks for reporting. Did you by any chance install/download new Signatures?

**Comment by sanchocho** [comment]
I also got this when I restart the machine.
It worked fine before restarting the server.
I do not install/download new signatures.
But when I analyzing the samples, it freeze and the screen is no-response.
that's why I restart the machine and then I got this message.

Cuckoo Sandbox 2.0.5
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

Oops! Cuckoo failed in an unhandled exception!
Sometimes bugs are already fixed in the development release, it is therefore recommended to retry with the latest development release available https://github.com/cuckoosandbox/cuckoo
If the error persists please open a new issue at https://github.com/cuckoosandbox/cuckoo/issues

=== Exception details ===
Cuckoo version: 2.0.5
OS version: posix
OS release: Ubuntu 14.04 trusty
Python version: 2.7.6
Python implementation: CPython
Machine arch: x86_64
Modules: adium-theme-ubuntu:0.3.4 alembic:0.8.8 androguard:3.0.1 apt-xapian-index:0.45 asn1crypto:0.24.0 beautifulsoup4:4.5.3 bottle:0.12.0 cairocffi:0.8.0 cairosvg:1.0.22 capstone:3.0.5rc2 cffi:1.11.5 chardet:2.3.0 click:6.6 colorama:0.3.7 command-not-found:0.3 cryptography:2.2.2 cssselect2:0.2.1 cuckoo:2.0.5.3 cybox:2.0.1.4 debtagshw:0.1 defer:1.0.6 dirspec:13.10 distorm3:3 distribute:0.7.3 django-extensions:1.6.7 django:1.8.4 dnspython:1.11.1 dpkt:1.8.7 duplicity:0.6.23 ecdsa:0.13 egghatch:0.2.1 elasticsearch:5.3.0 enum34:1.1.6 flask-sqlalchemy:2.1 flask:0.12.2 functools32:3.2.3.post2 html5lib:0.999999999 httplib2:0.8 httpreplay:0.2.2 idna:2.6 ipaddress:1.0.19 ipy:0.81 itsdangerous:0.24 jinja2:2.9.6 jsbeautifier:1.6.2 jsonschema:2.6.0 libvirt-python:1.2.2 lockfile:0.8 lxml:3.3.3 m2crypto:0.24.0 maec:4.0.1.0 magic-file-extensions:0.2 mako:1.0.7 markupsafe:1.0 meld3:0.6.10 ndg-httpsclient:0.4.0 oauthlib:0.6.1 olefile:0.43 oletools:0.51 oneconf:0.3.7.14.4.1 pam:0.4.2 pdfrw:0.4 peepdf:0.3.6 pefile2:1.2.11 pefile:1.2.9.1 pexpect:3.1 pillow:3.2.0 pip:9.0.1 piston-mini-client:0.7.5 psycopg2:2.7.4 pyasn1:0.1.8 pycparser:2.18 pycrypto:2.6.1 pycups:1.9.66 pydeep:0.4 pyelftools:0.24 pygobject:3.12.0 pymisp:2.4.54 pymongo:3.0.3 pyopenssl:17.5.0 pyphen:0.9.4 pyserial:2.6 pysmbc:1.0.14.1 python-apt:0.9.3.5ubuntu2 python-dateutil:2.4.2 python-debian:0.1.21-nmu2ubuntu2 python-editor:1.0.3 python-magic:0.4.12 pythonaes:1.0 pyxdg:0.25 reportlab:3.0 requests:2.13.0 scapy:2.3.2 sessioninstaller:0.0.0 setuptools:36.6.0 sflock:0.2.20 six:1.11.0 software-center-aptd-plugins:0.0.0 sqlalchemy:1.0.8 ssh-import-id:3.21 supervisor:3.0b2 system-service:0.1.6 tinycss2:0.6.1 tlslite-ng:0.6.0 twisted-core:13.2.0 twisted-web:13.2.0 typing:3.5.3.0 unicorn:1.0.1 unity-lens-photos:1.0 urllib3:1.22 vboxapi:1.0 virtualenv:1.11.4 volatility:2.3.1 wakeonlan:0.2.2 weasyprint:0.41 webencodings:0.5.1 werkzeug:0.14.1 wheel:0.24.0 wxpython-common:2.8.12.1 wxpython:2.8.12.1 xdiagnose:3.6.3build2 yara-python:3.6.3 zope.interface:4.0.5

2018-04-05 10:06:33,519 [cuckoo] ERROR: TypeError: an integer is required
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 230, in main
    cuckoo_init(level, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 114, in cuckoo_init
    if pidfile.exists():
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/misc.py", line 243, in exists
    return self.proc_exists(self.read())
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/misc.py", line 270, in proc_exists
    os.kill(pid, 0)
TypeError: an integer is required

**Comment by jbremer** [comment]
Thanks @sanchocho, I've created a fix for the bug you described.
For lack of additional from @maorlevi25 I'm closing this issue - feel free to reopen.
