### ISSUE TITLE
Cuckoo does not correctly handle unknown types. For example, .iso, .7z. Because of the type of parameter “Analyzer.config.package”.

### ISSUE THREAD

**Issue by mygodwzy** [cuckoosandbox/cuckoo#2266]
Specific position: 【cuckoo/cuckoo/data/analyzer/windows/analyzer.py@540】
Specific reasons: From web module of cuckoo sandbox, the package parameter is a string type. If the analyzed targed is unknown file type, the value of the package parameter is a string "None", this can cause misjudgment.
My solution: @540 =》【if not self.config.package or self.config.package.lower() in ("none", "null"):】

Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

**Comment by doomedraven** [comment]
you can just write the packages to extend support for that isn't support out of the box

**Comment by mygodwzy** [comment]
In analyzer of guest host, I've already realized one package for analyzing ISO file.
But I upload one ISO file from web page, the ISO analyzing package does not work.
Because it can't identify the ISO file, to choose the ISO analyzing package.



691385756@qq.com
 
发件人： doomedraven
发送时间： 2018-05-14 16:00
收件人： cuckoosandbox/cuckoo
抄送： wzy; Author
主题： Re: [cuckoosandbox/cuckoo] Cuckoo does not correctly handle unknown types. For example, .iso, .7z. Because of the type of parameter “Analyzer.config.package”. (#2266)
you can just write the packages to extend support for that isn't support out of the box

**Comment by doomedraven** [comment]
yes bcz if you check the documentation you will see that installing package in host isn't the same what add package to cuckoo to recognize correctly filetypes etc, check documentation ;)

**Comment by mygodwzy** [comment]
I know it. I am now adding ISO file type to cuckoo web module.
The code:【var default_package_selection_options = ['default', 'com', 'cpl', 'dll', 'doc', 'exe', 'generic', 'ie', 'ff', 'jar', 'js', 'jse', 'hta', 'msi', 'pdf', 'ppt', 'ps1', 'pub', 'python', 'vbs', 'wsf', 'xls', 'zip', 'iso'];】
But cuckoo web module can't identify ISO file type, so it choose "default" package, and in analyzer there is a problem 【package.None not found】.
【In cuckoo web module, I cannot find documentation about it】

**Comment by doomedraven** [comment]
no, that only js, you need to write .py code for that also, https://github.com/cuckoosandbox/cuckoo/tree/master/cuckoo/data/analyzer/windows/modules/packages

**Comment by RicoVZ** [comment]
Hi mygodwzy,

You are right, the "None" string instead of an actual None value is confusing and causes errors. This was fixed in commit https://github.com/cuckoosandbox/cuckoo/commit/0eabfc467c6cbd317ee19c25a7a09a2a1f0e2395. This commit will be included in the next release of Cuckoo. After this, the analyzer should try to select the correct package.

Currently, ISO files are not supported with any analysis packages. To add support, a new analysis package will have to be added. This package should contain the logic on how you want it to be opened/started.

For more information on how to create a new analysis package, see https://cuckoo.sh/docs/customization/packages.html (it also contains some examples) This is an addition to the logic that is executed on the analysis machine (the guest).

To use your new analysis package, you should add it to `$CWD/analyzer/windows/modules/packages` (Assuming your guest uses Windows).

**Comment by jbremer** [comment]
ISO files are supported as archive format though, i.e., `sflock` will unpack files from ISO files. Also, this bug has been resolved in the commit linked by @RicoVZ. Closing issue as resolved. Thanks for reporting.

**Comment by twesterhever** [comment]
One thing to notice here is that Cuckoo does not specify wether an analysis was aborted because of unknown file type or a file was "clean": The agent in VM just dies, and the result equals pretty much that one of the VM baselining report.

**Comment by doomedraven** [comment]
provide `pip freeze | grep sflock`
