### ISSUE TITLE
Cuckoo rooter not starting automatically

### ISSUE THREAD

**Issue by techchetn** [cuckoosandbox/cuckoo#2283]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My Cuckoo version and operating system are: Ubuntu 16.04
VMware Workstation Pro 12 running Windows

**Comment by techchetn** [comment]
Thanks, 

When i run cuckoo -d i'm getting below error.

"CuckooStartupError: The rooter is required but it is either not running or it has been configured to a different Unix socket path. Please refer to the documentation on working with the rooter."

Also, when i checked supervisor.conf, i found that unix.sock is missing from supervisord folder, does these error relates to the error i'm getting

**Comment by RicoVZ** [comment]
Hi techchetn,

Did you add Cuckoo Rooter to your supervisord? The error seems to be triggered because of a Rooter that is not running. The unix socket location is configured in `cuckoo.conf` and has a default value which should work for Linux systems.

I have found two issues which might helped you. They discuss about how to start Rooter automatically and provide some example `supervisord.conf` files and ways to do it using `systemd`.

https://github.com/cuckoosandbox/cuckoo/issues/2025#issuecomment-364672209
https://github.com/cuckoosandbox/cuckoo/pull/1856#issuecomment-381243835
https://github.com/cuckoosandbox/cuckoo/issues/2025#issue-283343997

**Comment by techchetn** [comment]
Hi Rico,

I've tried above, supervisord and creating a startup script is also not working, i think my setup is weird i don't find cuckoo in /opt folder

Any help ?

**Comment by RicoVZ** [comment]
@techchetn 
The `opt` path in the example happens to be the path where that user has their Cuckoo installation. They use a virtualenv.

The path should be replaced with where your cuckoo startup file is located. If you use a virtualenv, it will be in the `bin` folder of that virtualenv. Use `which cuckoo` to find your cuckoo bin path otherwise.

So it should be `command = <path to dir where cuckoo bin is located>/cuckoo rooter`.

**Comment by jbremer** [comment]
Closing issue for lack of additional information - please reopen if you have an update for us.
