### ISSUE TITLE
VirusTotal button

### ISSUE THREAD

**Issue by Hemorragie** [cuckoosandbox/cuckoo#2294]
Hello everyone, 

First I have to say that, Cuckoo is awesome and works properly on my system. But I wonder if it is possible to create an option virusTotal when submitting a sample to Cuckoo ? I tried to find a way in the documentation but I came to the conclusion that I had to code it.
It could be useful to have such an option (on shell command) or button (on Web Interface) to enable or not the virus total analysis on demand.

##### My Cuckoo version and operating system are:
Ubuntu, cuckoo 2.0.5

**Comment by doomedraven** [comment]
Check configs i think it was already there

**Comment by RicoVZ** [comment]
Hi Hemorragie,

Thanks for posting an issue.

You are right, at the moment it is not possible to enabled/disable the Virustotal processing module per analysis.

It is currently only possible to completely disable it in your `processing.conf` under `[virustotal]` by setting `enabled =` to 'no'.

If you want it, a "quick" way to implement it would be to add some logic that checks for a specific task option here, and return instead of running the module.

https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/processing/virustotal.py#L33

**Comment by Hemorragie** [comment]
Thank you for your answers, I will check this.
