### ISSUE TITLE
Help!!! Unable to analysis the Flash file 

### ISSUE THREAD

**Issue by cssxn** [cuckoosandbox/cuckoo#2316]
Even I append `.swf` extension to  `cuckoo-master\analyzer\windows\lib\core\packages.py`

```
 elif "Macromedia Flash" in file_type or file_name.endswith(".swf"):
        return "swf"
```

and Added a start module to  `analyzer/windows/modules/packages/swf.py`

**swf.py**

```
from lib.common.abstracts import Package

class SWF(Package):
    def start(self, path):
        return self.execute("bin/flashplayer.exe", path, path)
```

Then it still can not identify the extension of `swf` file. 

The Cuckoo log:
```
  File "C:/tmph2bhxn/analyzer.py", line 798, in <module>
    success = analyzer.run()
  File "C:/tmph2bhxn/analyzer.py", line 580, in run
    "not exist.".format(package_name))
CuckooError: Unable to import package "modules.packages.None", does not exist.
```

**Comment by doomedraven** [comment]
it sound like bcz you using cuckoo mod for start, not v2

v2 https://github.com/cuckoosandbox/cuckoo/commit/ab1ad37dba3c7917534a74b12907a954c69244f1

**Comment by RicoVZ** [comment]
Hi cssxn,

Thanks for posting an issue.

It seems like you are using a different/older version Cuckoo. The way you have created an analyzer package seems fine. It was not selected due to a bug that was present in Cuckoo a version ago. This bug was fixed. 

It caused the automatic package selector to not see that no package was specified yet, and it would try to execute the "None" package (as you see in the error).

Update to the latest Cuckoo version (2.0.6.1) using `pip install -U cuckoo`, and this should not happen again. :smile:

**Comment by cssxn** [comment]
@RicoVZ @doomedraven   Thanks for that!
