### ISSUE TITLE
Issue with building frontend

### ISSUE THREAD

**Issue by capnspacehook** [cuckoosandbox/cuckoo#2320]
I have been trying to contribute to Cuckoo, and am currently in the process of overhauling a processing module. I have been trying to change it's webpage to show new data, but the webpage was just blank after I edited the html file. I discovered that was due to the fact that I never rebuilt the website with gulp. I followed the documentation to install NodeJS, npm, sass, and gulp. I successfuly build everything... almost everything. When I ran `gulp build` in `cuckoo/web/src`, the following error appeared:

```
Error in plugin 'sass'
Message:
    scss/main.scss
Error: File to import not found or unreadable: bourbon.
        on line 8 of scss/main.scss
>>  @import "bourbon"; // <== sass utility framework

   -^
```

I installed bourbon without errors with `gem install bourbon`, so why is this error popping up?

**Comment by automagisch** [comment]
Hey! Thanks for reporting this issue, nice to see that you're interested in using the front-end build system, and I'm glad to help you out here. It's still an evolving prototype of something that has to be more and more robust overtime, with less dependencies, so if you have any suggestions to implement / change over time I'm all ear :)

But, about the issue:

This bourbon package is not managed by gem, but it's imported as a bower component, you can install it through `bower install --save bourbon` (source: https://github.com/thoughtbot/bourbon)

I hope this helps, it may have not installed properly on init because it's missing out of the `bower.json` dependency list. This will be fixed in a future version.

Good luck!

**Comment by capnspacehook** [comment]
Thanks for the prompt response! I'll try that tonight after work and let you know if I have any other questions!

**Comment by capnspacehook** [comment]
Worked great, thanks!
