### ISSUE TITLE
The processing module "Suricata" returned the following error:

### ISSUE THREAD

**Issue by 1623664** [cuckoosandbox/cuckoo#2402]
WARNING: The processing module "Suricata" returned the following error: Suricata returned an error processing this pcap: Command '['/usr/bin/suricata', '-c', '/etc/suricata/suricata-cuckoo.yaml', '-k', 'none', '-l', '/home/cuckoo/.cuckoo/storage/analyses/32/suricata', '-r', '/home/cuckoo/.cuckoo/storage/analyses/32/dump.pcap']' returned non-zero exit status 1

**Comment by RicoVZ** [comment]
Hi 1623664,

Thanks for posting an issue.

Please follow the issues templates, it helps us to more quickly determine what the issue is. :smile: What is your Cuckoo version and the OS of the Cuckoo host?

A more detailed Cuckoo log would help a lot. Could you post the `cuckoo.log` of the analysis for which this is happening? :smile: You can find it at `$CWD/storage/analyses/<taskid>/cuckoo.log`

I wonder what the output of Suricata is. Could you run the following command manually and also post its output?
```
/usr/bin/suricata -c /etc/suricata/suricata-cuckoo.yaml -k none -l /home/cuckoo/.cuckoo/storage/analyses/32/suricata -r /home/cuckoo/.cuckoo/storage/analyses/32/dump.pcap
```

**Comment by 1623664** [comment]
Thank you. Found an error. Improperly configured suricata-cuckoo.yaml
