### ISSUE TITLE
 Cuckoo evaluates all files as safe

### ISSUE THREAD

**Issue by foolishhare** [cuckoosandbox/cuckoo#2554]
Cuckoo don`t analyse any malware file. I try analyse testing file "eicar" and some my Trojans which i find in internet. But they all safe))
Cuckoo version 2.0.6
Attach cuckoo log file and few screenshot.
[cuckoo.log](https://github.com/cuckoosandbox/cuckoo/files/2572360/cuckoo.log)
![screenshot_1](https://user-images.githubusercontent.com/14123319/48355454-be7dc400-e69c-11e8-8a37-23ecc151db05.png)
![screenshot_2](https://user-images.githubusercontent.com/14123319/48355455-be7dc400-e69c-11e8-882f-8a36a4722436.png)

**Comment by doomedraven** [comment]
hey did you check the outout of cuckoo? im pretty sure there is one green like to exec `cuckoo community`

**Comment by RicoVZ** [comment]
Hi foolishhare,

Thanks for posting an issue.

As @doomedraven pointed out, this is more likely because you do not have any Cuckoo signatures. You can install by them with the `cuckoo community` command.

Be careful, when a Cuckoo score is low, it is no guarantee a file is safe. It simply means no behavior was collected in which the signatures find patterns that are deemed malicious. This can also happen if a sample crashes, does not run long enough, missing signatures, or when a sample only performs certain actions under specific circumstances.

**Comment by foolishhare** [comment]
Yes, i forgot type that command)
