### ISSUE TITLE
Pillow does not take many screenshots?

### ISSUE THREAD

**Issue by SalehAce1** [cuckoosandbox/cuckoo#2658]
##### My issue is:
When I analyze a sample of Cerber, Cuckoo Sandbox only outputs one screenshot and that is only a picture of what the Desktop would look like at the start. Looking at the behavior log however, it is clear that the ransomware did in fact encrypt files because it used the API "CryptCreateHash" and "CryptHashData." Should I ignore the lack of screenshots or could the lack of screenshot evidence be proof that the ransomware is detecting it is in a VM?

##### My Cuckoo version and operating system are:
Windows 7 SP1 86x

##### The log, error, files etc can be found at:
This is the only screenshot I got, it shows nothing. 
![image](https://user-images.githubusercontent.com/32824461/52977321-d69b6880-339a-11e9-83a0-c72e4dd7a85e.png)

**Comment by maximedotdev** [comment]
Without logs it is difficult to speculate but a single screenshot would usually mean that no *visible* activity occurred. I've once had this issue which was caused by the ransomware not being executed due to Windows Defender still being enabled.

Are you sure the ransomware properly executes? You could try to manually start the virtual machine and manually execute the malware to check for proper execution.

**Comment by Rooobaaat** [comment]
If nothing visible happens, no screenshots will be taken. So this can be normal
