### ISSUE TITLE
API - specifying analysis options

### ISSUE THREAD

**Issue by mkrsfcmp** [cuckoosandbox/cuckoo#2745]
##### My issue is:
I'm trying to submit a sample to run with a DLL package and a specific function to run and cannot find the way to do it. (and documentation is quite vague on specifying options via API.

##### My Cuckoo version and operating system are:
cuckoo 2.0.6.2

##### This can be reproduced by:
Trying, for example:

/usr/bin/curl -v --noproxy -s -k -F file=@/tmp/8b7e2b0596b46f2f68a83ae31ee1072d -F options="function=PlayGame" https://192.168.2.2/cuckooapi/tasks/create/submit

But still cuckoo tries to run DllMain which is not present in the library.
Tried various methods of specifying options but none seems to work.
How can I specify option for a dll module?

**Comment by RicoVZ** [comment]
Hi @mkrsfcmp,

This is caused by the submit API endpoint. The logic behind it causes some options to be lost. It is something we are working on.

Using tasks/create/file should work.

`curl -v --noproxy -s -k -F file=@/tmp/8b7e2b0596b46f2f68a83ae31ee1072d -F options="function=PlayGame" https://192.168.2.2/cuckooapi/tasks/create/submit`

**Comment by mkrsfcmp** [comment]
That's one of the first ways I tried but unfortunately, it still doesn't work the way I need. So I understand that for now the option is silently dropped and there's not much I can do about it, right?

**Comment by RicoVZ** [comment]
Using /tasks/create/file instead of /tasks/create/submit does not work? 

Sorry, I just noticed I posted the wrong example. I have edited it. I meant:
`curl -v --noproxy -s -k -F file=@/tmp/8b7e2b0596b46f2f68a83ae31ee1072d -F options="function=PlayGame" https://192.168.2.2/cuckooapi/tasks/create/file`

**Comment by mkrsfcmp** [comment]
With tasks/create/file it does seem to work indeed. Thank you.

**Comment by qq854051086** [comment]
我想通过request发送样本，同时我指定了`unique`参数，但是server一直返回200，未出现过400。我该如何解决呢？或者，该参数不起作用吗。我这里不是分布式的。谢谢
