### ISSUE TITLE
rundll32 won't run dll files without ".dll" extension

### ISSUE THREAD

**Issue by jhumble** [cuckoosandbox/cuckoo#354]
For dll files without the .dll extension, Cuckoo will correctly select the dll package based off mime type. However, once the analyzer tries to run the file with Rundll32 it will fail because Rundll32 will not execute dlls without the extension.

I addressed this locally by just adding code to the dll package to rename the file, adding the dll extension if needed. Using os.rename to do that has the side effect of showing up in the dropped files section of the results.

I'm submitting this as an issue rather than a pull request because there's probably a more appropriate place to do this replacement before the file is already running on the guest.

**Comment by Marqo09** [comment]
If it's worth anything, rundll32.exe will handle DLLs without file extensions. When LdrLoadDll() is called under the hood, the ".dll" extension is automatically added. A great explanation of this can found on [this Poweliks blog](http://thisissecurity.net/2014/08/20/poweliks-command-line-confusion/). I'd be willing to bet that the previously discovered missing extension "issues" were actually related to search order resolution failures.

With that said, it might be more elegant to leverage ctypes.windll.LoadLibrary() within the DLL analysis package to provide a future proof way to call a DLL's exported functions and ordinals. Technically, rundll32.exe has been [deprecated since Vista](https://blogs.msdn.microsoft.com/oldnewthing/20130104-00/?p=5643)...
