### ISSUE TITLE
Analysis failed when executing non-ascii process name

### ISSUE THREAD

**Issue by supahal** [cuckoosandbox/cuckoo#502]
2015-03-23 11:42:08,124 [lib.cuckoo.core.scheduler] ERROR: Analysis failed: The package "modules.packages.xxx" start function encountered an unhandled exception: 'ascii' codec can't encode character u'\u202e' in position 4: ordinal not in range(128)

Sha1: 671b5f8dd4a5065ea25abbc88ac7b098c8c6d4b3

**Comment by r00t0vi4** [comment]
Maybe your database has latin1 charset. Must be utf8.
Use this code to create new database:
```
CREATE DATABASE cuckoo CHARACTER SET utf8 COLLATE utf8_general_ci
```

**Comment by jekil** [comment]
@r00t0vi4: sqlalchemy is using utf8 by default (http://docs.sqlalchemy.org/en/rel_0_9/core/engines.html).

**Comment by r00t0vi4** [comment]
This two steps resolve this bug:
In cuckoo.conf set:
```
connection = mysql://cuckoo:cuckoo@localhost/db?charset=utf8
```
Create database:
```
CREATE DATABASE cuckoo CHARACTER SET utf8 COLLATE utf8_general_ci
```

@jekil mysql default installation use latin1 character set. If using command "CREATE DATABASE cuckoo"

**Comment by jekil** [comment]
@r00t0vi4 if you are using a custom db, like mysql, the configuration is up to you, so it's your responsability to use a proper create statement (although i will add a note in the doc), and if you run the creation statement properly, adding charset=utf8 to the connection string is useless, it is already the default.

**Comment by botherder** [comment]
I'm not sure this is really a problem on how the file is stored in the database.

**Comment by jbremer** [comment]
It's not - I'll try to handle it for the upcoming release with the new injection utility.

**Comment by jbremer** [comment]
I have updated the injection utilitie(s) of the new monitor so that it supports unicode filenames. https://github.com/jbremer/monitor/commit/4795faddf788a9b4920b92677a4ba176b33c064b https://github.com/jbremer/monitor/commit/50e48b292fa110e38c703abc6ab8ac67be29a111 https://github.com/jbremer/monitor/commit/0d952d2607959aa25ef4045b1206cf8251afb2b7 (It turns out that some of the changes to `inject.c` were actually not necessary, such as parsing the command-line as unicode as we're using short paths anyway, but hey.. they don't hurt either).

On Cuckoo side I have removed sanitation of filenames and implemented a work-around for Python 2.7 which apparently does not support passing unicode strings along to the `subprocess` module. https://github.com/cuckoobox/cuckoo/commit/c807650ff7d9496a4d7637becdcf9d0bba47e795

You can test these changes by changing to the `monitor` branch of Cuckoo.

**Comment by jbremer** [comment]
Closing this issue as it works as expected for me - please reopen if you hit a bug or have more questions about it.

**Comment by Mediterranean90** [comment]
If the filename has Chinese characters, it doesn't work. I want to know how to resolve it.

**Comment by gugronnier** [comment]
same problem with name like "test_ℵªΩΨ♣.js" and "test_копии.js"

**Comment by jbremer** [comment]
I believe a newer feature broke this support again, we're aware of that indeed. I'll try to fix it soon'ish (as well as write some unit tests for it so we can assure it will not be an issue in the future).

**Comment by jbremer** [comment]
This has been fixed for our upcoming release now, closing the issue. Thanks for your feedback!
