### ISSUE TITLE
Web interface option to re-analyze previous tasks (particularly failed)

### ISSUE THREAD

**Issue by jpsenior** [cuckoosandbox/cuckoo#527]
There may be more than one instance of an administrator requiring a re-analysis of a previous task - e.g. mongodb wasn't running, virtualbox VM wasn't shut down properly, etc.  cuckoo.py process <task> can easily do this, so let's make a button "Retry Processing" or "Retry task" under web/analysis/views.py.

**Comment by botherder** [comment]
I like the idea.

**Comment by SpoonBoy** [comment]
duplicate of #483 ?
will take a look at this feature during the day or tomorrow.

**Comment by jbremer** [comment]
There's a `resubmit analysis` button nowadays which I guess is most of what you suggested here.
We could add `reprocessing` in the sense that the analysis task status could be set to `completed` and then wait for one of the `process.py` instances to pick it up, but it's a little bit dirty (would also have to delete all data from the MongoDB database before hand etc).
So going to close this as resolved for now - please reopen or create a new issue if you think otherwise.
