### ISSUE TITLE
Chinese filename web submit error issue

### ISSUE THREAD

**Issue by dingyuchi** [cuckoosandbox/cuckoo#603]
When submit a file which had chinese filename like "中文.exe", server will return 500 error: 
 ` 'ascii' codec can't encode characters in position 30-32: ordinal not in range(128)`

modify store_temp_file function in lib/cuckoo/common/utils.py 
add `filename = filename.encode("utf-8")` to solve this problem

> def store_temp_file(filedata, filename, path=None):
>     """Store a temporary file.
>     @param filedata: content of the original file.
>     @param filename: name of the original file.
>     @param path: optional path for temp directory.
>     @return: path to the temporary file.
>     """
>     filename = get_filename_from_path(filename)
>     filename = filename.encode("utf-8")
>     # Reduce length (100 is arbitrary).
>     filename = filename[:100]

**Comment by holdlg** [comment]
不清楚你的问题所在，cuckoo对中文确实存在这个问题，不至一处，包括cuckoomon.dll 对中文的支持也遇到过问题。

**Comment by why99fun** [comment]
建议后台改名后上传


来自 魅族 MX2

-------- 原始邮件 --------
发件人：holdlg <notifications@github.com>
时间：周二 7月21日 17:44
收件人：cuckoobox/cuckoo <cuckoo@noreply.github.com>
主题：Re: [cuckoo] Chinese filename web submit error issue (#603)

**Comment by jbremer** [comment]
I understand that we have an issue with unicode filenames, but it'd still be nice if you could communicate in English here :-P

**Comment by why99fun** [comment]
我觉得应当有个中文社区，create chinese forum to communicate like that chinatown



来自 魅族 MX2

-------- 原始邮件 --------
发件人：Jurriaan Bremer <notifications@github.com>
时间：周二 7月21日 18:26
收件人：cuckoobox/cuckoo <cuckoo@noreply.github.com>
抄送：houyi wang <why99fun@163.com>
主题：Re: [cuckoo] Chinese filename web submit error issue (#603)

**Comment by jhg** [comment]
@why99fun this not is a chinesse comunity, I'm from Spain (Canary Island, Spain), @jbremer is from Amsterdam (read in Github profile), @igorcaavalcante (of https://github.com/cuckoobox/cuckoo/pull/533 PR) speak portuguese. I think this is a development with a international comunity with a lot of languages, and not is chinesse people better that other, here all speak English for all understand to other people. If you want proposal a auxiliary language better that english, then proposal esperanto for example, but not is a good way that as you speak chinesse then force to all people to not understand. Forums for give support to people that don't speak english in multiple languages I think is good, but force languages and isolation here not, that is bad. If you want proposal other auxiliary language, then proposal this and that comunity choice, but not force to chinesse because that only isolate to people because chinesse is difficult, has thousand and thousand of chars and other languages as esperanto, english or others is more easy for all people, and not can force your language, other people speak with auxiliar language here and not force own language.

**Comment by jbremer** [comment]
Well, well, let's all relax for a minute. It's not that big of an issue, just a request in general to keep the language somewhat regulated ;)

**Comment by dingyuchi** [comment]
I take a screenshot:

![2015-07-22_084612](https://cloud.githubusercontent.com/assets/250563/8815654/85de944c-304e-11e5-908c-76cbb116cb8c.png)

uname -a
> Linux cuckoo 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:56:17 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

locale

> LANG=en_US.UTF-8
> LANGUAGE=
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC=zh_TW.UTF-8
> LC_TIME=zh_TW.UTF-8
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY=zh_TW.UTF-8
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER=zh_TW.UTF-8
> LC_NAME=zh_TW.UTF-8
> LC_ADDRESS=zh_TW.UTF-8
> LC_TELEPHONE=zh_TW.UTF-8
> LC_MEASUREMENT=zh_TW.UTF-8
> LC_IDENTIFICATION=zh_TW.UTF-8
> LC_ALL=

**Comment by jbremer** [comment]
Can you provide a filename that gives errors when submitting? I'm testing this against the latest version in `master` and not getting any errors with unicode filenames. (I'd assume that if Chinese filenames fail, generic Unicode filenames would also fail, but so far no *luck*).

**Comment by jekil** [comment]
I also tried with latest master, with my locale conf and the posted one, no errors.
@dingyuchi could you please add more details or test the latest release from github?

**Comment by jbremer** [comment]
Closing this issue as fixed, thanks all.
