### ISSUE TITLE
MySQL issues with Distributed Cuckoo

### ISSUE THREAD

**Issue by jbremer** [cuckoosandbox/cuckoo#646]
As reported by Florian Eichelberger Distributed Cuckoo has the following issues. So test with MySQL and resolve them later on.

```
sqlalchemy.exc.CompileError: (in table 'alembic_version', column 'version_num'): VARCHAR requires a length on dialect mysql
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1170, "BLOB/TEXT column 'version_num' used in key specification without a key length") [SQL: u'\nCREATE TABLE alembic_version (\n\tversion_num TEXT NOT NULL, \n\tPRIMARY KEY (version_num)\n)\n\n']
```

**Comment by botherder** [comment]
Updates?

**Comment by wkupersa** [comment]
FWIW The issue is the unique constraint on the name column of the node table. Mysql won't let you enforce Unique unless you tell it how much of the field needs to be unique. 

This DDL works in mysql. 

'''
CREATE TABLE node (id INTEGER NOT NULL AUTO_INCREMENT,  name TEXT NOT NULL,  url TEXT NOT NULL,  mode TEXT NOT NULL,  enabled BOOL NOT NULL,  PRIMARY KEY (id), UNIQUE (name(255)));
'''
Unfortunately I don't know how to implement that in sqlalchemy yet for the necessary changes in distributed/db.py

**Comment by jbremer** [comment]
`db.String(255)` I think - could you try that?

**Comment by wkupersa** [comment]
Worked like a charm! Fell through to the next case where the alembic version number did the same thing.  Here's a diff. 

```
11,13d10
<
<
<
48c45
<     name = db.Column(db.String(255), nullable=False, unique=True)
---
>     name = db.Column(db.Text, nullable=False, unique=True)
154c151
<     version_num = db.Column(db.String(16), nullable=False, primary_key=True)
---
>     version_num = db.Column(db.Text, nullable=False, primary_key=True)
```

**Comment by wkupersa** [comment]
Apparently I am still missing something because the node_status table never gets populated and tasks pile up. I see the section of api.py where the node is added but I don't see where node_Status is updated.

**Comment by jbremer** [comment]
This issue has finally been addressed & resolved, thanks to all involved. Closing this issue.
