### ISSUE TITLE
I think we can use Python's gc.collect() to release the memory of results, to avoid memory leaks.

### ISSUE THREAD

**Issue by sunway1988** [cuckoosandbox/cuckoo#711]
```python
 # Respawn a worker process every 1000 tasks just in case we
 # have any memory leaks.
 pool = multiprocessing.Pool(processes=parallel, initializer=init_worker,
                                maxtasksperchild=1000)
```

The above could solve the memory leaks, but I think a better way is to use manual gc(`gc.collect()`), because compared to the analysis, reports processing is faster, that is to say we can tolerate the influence caused by gc. At this way, we can avoid the leaks instead of respawn the worker process after 1000 tasks passed with the memory going higher.

So the solution is like:
```python
del results
gc.collect()
```
Add the two lines after we have used results in `RunProcessing()` and don't need it any more.

**Comment by jbremer** [comment]
The whole `multiprocessing` thing is not working out very nicely in the first place, which is why I made a start on `process2.py`. The problem appears to be `multiprocessing` freezing up sort of randomly and therefore not processing any more tasks.
So aside from not having a lot of interest in *improving* `process.py`, I also don't think that the suggested change does any improvements over just using a new worker every 1000 tasks. Stopping a worker and starting a new one really is not expensive CPU-wise so I don't see a reason to change that.

Closing this issue, but if you have other counter arguments feel free to re-open it.
