### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by patilswapnilb** [cuckoosandbox/cuckoo#742]
After submitting malware for analysis, i am getting this error.

 Cuckoo Sandbox 2.0-dev
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
 Outdated! Cuckoo Sandbox version 2.0-rc1 is available now.

**tcpdump: vboxnet0: That device is not up**
**ERROR: Timeout hit while for machine windowsxp to change status**
 **CRITICAL: A critical error has occurred trying to use the machine with name windowsxp during an analysis due to which it is no longer in a working state, please report this issue and all of the related environment details to the developers so we can improve this situation. (Note that before we would simply remove this VM from doing any more analyses, but as all the VMs will eventually be depleted that way, hopefully we'll find a better solution now).**

 **WARNING: Unable to stop machine windowsxp: Trying to stop an already stopped vm windowsxp**
 **WARNING: Analysis results folder does not exist at path .**
 **WARNING: The PCAP file does not exist at path .**

**Any ideas on how can I get fixed  this please ?**

**Comment by patilswapnilb** [comment]
@botherder can you please help me on this error....

**Comment by botherder** [comment]
Well, you have multiple problems. Firstly, you don't have vboxnet0 properly configured since tcpdump can't see it. Secondly, the VM it is not starting. It might not start because it is configured to use vboxnet0 and the device doesn't exist? Check your VirtualBox preferences.
Then try to start the VM manually and see what happens.

FWIW, for this type of help, I'd prefer if you'd use community.cuckoosandbox.org instead of GitHub Issues.

**Comment by patilswapnilb** [comment]
thank you
