### ISSUE TITLE
the cpu load of the cuckoo process is always higher than 100% ,near 200%

### ISSUE THREAD

**Issue by xvsfekcn** [cuckoosandbox/cuckoo#758]
my machine is have 128G ram and the cpu is have 24 core.
but the one python process only use one cpu core,due this i think when run many VM,the cuckoo process maybe only use one cpu core.so my centos6.5 with xen is very slow.

**Comment by xvsfekcn** [comment]
And I want to know  why not use the multiprocessing to do the analysis

**Comment by jbremer** [comment]
Well, `multiprocessing` is pretty unstable in my experience (had many issues because of it with `utils/process.py`). Also I believe one of our reasons not to use multiple processes in the past was because `sqlite3` - our default database handler - doesn't handle multiple processes very well.

Is there anything concrete you'd like to address in this issue?

**Comment by jimmythegreat** [comment]
You could try disabling processing in the main cuckoo instance and run utils/process.py instead. This will help alleviate some of the issues with python's GIL.

**Comment by jbremer** [comment]
It is on our longer term todo list to improve a couple of different performance-related issue, but I'm going to close this issue as it doesn't add much to those goals and future improvements.
