### ISSUE TITLE
No antivirus signatures available.

### ISSUE THREAD

**Issue by SmileLow** [cuckoosandbox/cuckoo#829]
![image](https://cloud.githubusercontent.com/assets/13845992/14096222/89518e3e-f599-11e5-9f79-46997bf49e7d.png)

**Comment by MeteorAdminz** [comment]
hello SmileLow,

No antivirus signature available on virustotal is because there is no one uploaded the file/url. You can check it when you go to virustotal and then try to make a search for the hash/url if virustotal returned no result this mean it will cause the cuckoo sandbox can't get the antivirus signature.

**Comment by botherder** [comment]
What he said.
