### ISSUE TITLE
No Screenshots available

### ISSUE THREAD

**Issue by threedanes** [cuckoosandbox/cuckoo#831]
All,

I am using the latest Cuckoo code and when I submit a URL I am not getting any screenshots.  I saw the error for "Could not find tesseract binary, screenshot OCR aborted."   I verified that the Processing.conf screenshots are enabled
[screenshots]
enabled = yes
tesseract = /usr/bin/tesseract

From there I installed tesseract-OCR, did a reboot and run another submission. 

It still does not have any screenshots and I am wondering if I missed something.  Thanks for any help or direction

/R 

Thomas

**Comment by BlackyFox** [comment]
Hi Thomas! 

I had the same error but found where the mistake was (at least for me...). 
You need to check the path of your tesseract installation. Mine wasn't in `/usr/bin/tesseract` but in `/usr/bin/include/tesseract` (due to path configuration during the compilation).

I changed the path in the processing.conf file and it resolved the errors.
But I don't have any screenshot on the other hand...
And I have the Python Image Library installed in the clients.

Antoine

**Comment by threedanes** [comment]
well I am going to hang my head in shame and walk away slowly.  As soon as i saw the Python Image Lib I slapped my forehead knowing i forgot to install that.

Thank you for the memory check Antoine!

/R 

Thomas

**Comment by BlackyFox** [comment]
You're welcome! 

But, I also solved my problem in the meantime! Don't install PIL but Pillow on your sandbox guest. Since PIL is deprecated, it's better to work with the up-to-date fork, Pillow. Hopefully, this will work for you too.

Antoine

**Comment by threedanes** [comment]
Awesome I will give that a go, I am about to spin up another Cuckoo server I will give that one a shot.

Thomas
