### ISSUE TITLE
http vs http_ex

### ISSUE THREAD

**Issue by milesarmstrong** [cuckoosandbox/cuckoo#891]
Hi

Please could you explain the difference between the http and http_ex section in the network section of the report?

I notice that http_ex / https_ex don't appear in Cuckoo 1.2, so I wonder if this is a new feature and http is left in for backwards compatibility?

Thanks

**Comment by jbremer** [comment]
Sure thing, `http_ex` and `https_ex` are new entries. They contain the full HTTP requests - based on the `httpreplay` library - rather than what we had before, which was pretty much just looking at the first packet.
And thus, yes, it's a new feature and yes, the old stuff is still in there for backwards compatibility.

**Comment by milesarmstrong** [comment]
Thanks :+1:
