### ISSUE TITLE
Error when memory dump is enabled (ESX)

### ISSUE THREAD

**Issue by deloittem** [cuckoosandbox/cuckoo#927]
Hello,

I'd like to use Volatility with Cuckoo, so I enabled the memory dump feature. I'm using ESX and I always receive the following error:

2016-05-18 14:05:10,511 [lib.cuckoo.common.abstracts] DEBUG: Dumping memory for machine cuckoo
libvirt: Domain Config error : this function is not supported by the connection driver: virDomainCoreDump
2016-05-18 14:05:10,512 [lib.cuckoo.core.scheduler] ERROR: Error dumping memory virtual machine cuckoo: this function is not supported by the connection driver: virDomainCoreDump

Does anyone know what the problem is ?

Thank you

**Comment by KillerInstinct** [comment]
Use the vsphere machinery instead of the esx one.

**Comment by deloittem** [comment]
Is it really not possible to make it working with ESX ?

**Comment by deloittem** [comment]
Btw what about the memory_dump switch ? According to the comments:

     Currently available for: VirtualBox and libvirt modules

**Comment by KillerInstinct** [comment]
memory_dump is just a 'virDomainCoreDump' which according to https://libvirt.org/hvsupport.html is not supported for the ESX driver.

the vSphere module will dump memory from ESX because it uses VMware's python bindings and not libvirt. You'd just need to pip install pyvmomi for it to work.

**Comment by certau-davidg** [comment]
I attempted to post a fix for this back on May 23rd saying we had wrote some code to handle the memory dump without vsphere (using libvirt). Unsure if the comment was deleted or did not save. Code and config modifications here:
[Pastebin esx.conf](http://pastebin.com/SfY67tcx)
[Pastebin esx.py](http://pastebin.com/Xbh6TzTB)

**Comment by carine35000** [comment]
Hi, I m a french girl so sorry for the possible mistakes.
The links to esx.conf and esx.py have disappear.
Could you put again the soluce pastebin esx.conf and esx.py please
Thanks
PS : I m working and vsphere but if I configure vsphere.conf cuckoo.py doesn't load sphere unable to import vsphere so I work with the esx.conf

**Comment by certau-davidg** [comment]
Hi Carine,
I set the pastebin links to expire in order to encourage deprecation of the esxi module as per the authors stated plans.
According to jgajek in [cuckoo issue #975](https://github.com/cuckoosandbox/cuckoo/issues/975) the vsphere module has been tested and works with esxi.
We haven't had a chance to test this yet ourselves, but you should probably look at testing the supported vsphere module instead of attempting to support a forked module.

**Comment by carine35000** [comment]
Hi, 

I've tried with vshpere.com and it works very well 

Thanks you 


----- Mail original -----

De: "certau-davidg" <notifications@github.com> 
À: "cuckoosandbox/cuckoo" <cuckoo@noreply.github.com> 
Cc: "carine35000" <carine.selles@laposte.net>, "Comment" <comment@noreply.github.com> 
Envoyé: Lundi 30 Janvier 2017 04:27:40 
Objet: Re: [cuckoosandbox/cuckoo] Error when memory dump is enabled (ESX) (#927) 



Hi Carine, 
I set the pastebin links to expire in order to encourage deprecation of the esxi module as per the authors stated plans. 
According to jgajek in cuckoo issue #975 the vsphere module has been tested and works with esxi. 
We haven't had a chance to test this yet ourselves, but you should probably look at testing the supported vsphere module instead of attempting to support a forked module.
